#!/usr/bin/env python
# -*- coding: utf-8 -*-
# generated by wxGlade cdc33fbee011 on Mon Mar 15 21:45:01 2010

import wx

# begin wxGlade: extracode
# Widgewt IDs
ID_ABOUT = 101
ID_EXIT  = 102
ID_IMPORT= 103
ID_EXPORT= 104
ID_PREF  = 105
ID_HELP  = 106
ID_CLOSE = 107
ID_IMPORT_DATA = 113
ID_IMPORT_DATA_BATCH = 213
ID_IMPORT_DATA_HOST = 313
ID_IMPORT_QUERIES = 123
ID_EXPORT_GRAPHS = 114
ID_EXPORT_COLS  =124
ID_EXPORT_QUERIES = 134
ID_CLOSE_DATASET = 117
from  esxp_gui_custom import *
# end wxGlade



class EsxPlotPreferencesDialog(wx.Dialog):
    def __init__(self, *args, **kwds):
        # begin wxGlade: EsxPlotPreferencesDialog.__init__
        kwds["style"] = wx.DEFAULT_DIALOG_STYLE
        wx.Dialog.__init__(self, *args, **kwds)
        self.label_glc = wx.StaticText(self, -1, "Graph Line Colors")
        self.spacer_01 = wx.StaticText(self, -1, "")
        self.spacer_02 = wx.StaticText(self, -1, "")
        self.spacer_03 = wx.StaticText(self, -1, "")
        self.label_plot_line_1 = wx.StaticText(self, -1, "Plot Line 1:")
        self.tcl_rgb1 = wx.TextCtrl(self, -1, "midnightblue")
        self.label_plot_line_9 = wx.StaticText(self, -1, "Plot Line 9:")
        self.tcl_rgb9 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_2 = wx.StaticText(self, -1, "Plot Line 2:")
        self.tcl_rgb2 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_10 = wx.StaticText(self, -1, "Plot Line 10:")
        self.tcl_rgb10 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_3 = wx.StaticText(self, -1, "Plot Line 3:")
        self.tcl_rgb3 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_11 = wx.StaticText(self, -1, "Plot Line 11:")
        self.tcl_rgb11 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_4 = wx.StaticText(self, -1, "Plot Line 4:")
        self.tcl_rgb4 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_12 = wx.StaticText(self, -1, "Plot Line 12:")
        self.tcl_rgb12 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_5 = wx.StaticText(self, -1, "Plot Line 5:")
        self.tcl_rgb5 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_13 = wx.StaticText(self, -1, "Plot Line 13:")
        self.tcl_rgb13 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_6 = wx.StaticText(self, -1, "Plot Line 6:")
        self.tcl_rgb6 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_14 = wx.StaticText(self, -1, "Plot Line 14:")
        self.tcl_rgb14 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_7 = wx.StaticText(self, -1, "Plot Line 7:")
        self.tcl_rgb7 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_15 = wx.StaticText(self, -1, "Plot Line 15:")
        self.tcl_rgb15 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_8 = wx.StaticText(self, -1, "Plot Line 8:")
        self.tcl_rgb8 = wx.TextCtrl(self, -1, "")
        self.label_plot_line_16 = wx.StaticText(self, -1, "Plot Line 16:")
        self.tcl_rgb16 = wx.TextCtrl(self, -1, "")
        self.button_color_reset = wx.Button(self, -1, "reset colors")
        self.chkb_lgd = wx.CheckBox(self, -1, "Abbreviated Legends")
        self.tcl_lgd = wx.TextCtrl(self, -1, "")
        self.label_glw = wx.StaticText(self, -1, "Graph Line Width :")
        self.radio_linew1 = wx.RadioButton(self, -1, "1", style=wx.RB_GROUP)
        self.radio_linew2 = wx.RadioButton(self, -1, "2")
        self.cancelButton = wx.Button(self, wx.ID_CANCEL, "Cancel")
        self.okButton = wx.Button(self, wx.ID_OK, "OK")

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: EsxPlotPreferencesDialog.__set_properties
        self.SetTitle("Preferences")
        self.SetSize((565, 378))
        self.label_glc.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.tcl_rgb1.SetMinSize((80, 20))
        self.label_plot_line_9.SetMinSize((80, 20))
        self.tcl_rgb9.SetMinSize((80, 20))
        self.tcl_rgb2.SetMinSize((80, 20))
        self.tcl_rgb10.SetMinSize((80, 20))
        self.tcl_rgb3.SetMinSize((80, 20))
        self.tcl_rgb11.SetMinSize((80, 20))
        self.tcl_rgb4.SetMinSize((80, 20))
        self.tcl_rgb12.SetMinSize((80, 20))
        self.tcl_rgb5.SetMinSize((80, 20))
        self.tcl_rgb13.SetMinSize((80, 20))
        self.tcl_rgb6.SetMinSize((80, 20))
        self.tcl_rgb14.SetMinSize((80, 20))
        self.tcl_rgb7.SetMinSize((80, 20))
        self.tcl_rgb15.SetMinSize((80, 20))
        self.tcl_rgb8.SetMinSize((80, 20))
        self.tcl_rgb16.SetMinSize((80, 20))
        self.button_color_reset.SetMinSize((88, 22))
        self.chkb_lgd.SetMinSize((185, 20))
        self.chkb_lgd.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        self.tcl_lgd.SetMinSize((80, 20))
        self.label_glw.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: EsxPlotPreferencesDialog.__do_layout
        pref_sizer_1 = wx.FlexGridSizer(14, 4, 2, 6)
        pref_sizer_1.Add(self.label_glc, 0, wx.ALL, 8)
        pref_sizer_1.Add(self.spacer_01, 0, 0, 0)
        pref_sizer_1.Add(self.spacer_02, 0, 0, 0)
        pref_sizer_1.Add(self.spacer_03, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_1, 0, wx.LEFT, 90)
        pref_sizer_1.Add(self.tcl_rgb1, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_9, 0, wx.SHAPED|wx.FIXED_MINSIZE, 0)
        pref_sizer_1.Add(self.tcl_rgb9, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_2, 0, wx.LEFT, 90)
        pref_sizer_1.Add(self.tcl_rgb2, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_10, 0, 0, 0)
        pref_sizer_1.Add(self.tcl_rgb10, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_3, 0, wx.LEFT, 90)
        pref_sizer_1.Add(self.tcl_rgb3, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_11, 0, 0, 0)
        pref_sizer_1.Add(self.tcl_rgb11, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_4, 0, wx.LEFT, 90)
        pref_sizer_1.Add(self.tcl_rgb4, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_12, 0, 0, 0)
        pref_sizer_1.Add(self.tcl_rgb12, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_5, 0, wx.LEFT, 90)
        pref_sizer_1.Add(self.tcl_rgb5, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_13, 0, 0, 0)
        pref_sizer_1.Add(self.tcl_rgb13, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_6, 0, wx.LEFT, 90)
        pref_sizer_1.Add(self.tcl_rgb6, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_14, 0, 0, 0)
        pref_sizer_1.Add(self.tcl_rgb14, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_7, 0, wx.LEFT, 90)
        pref_sizer_1.Add(self.tcl_rgb7, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_15, 0, 0, 0)
        pref_sizer_1.Add(self.tcl_rgb15, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_8, 0, wx.LEFT, 90)
        pref_sizer_1.Add(self.tcl_rgb8, 0, 0, 0)
        pref_sizer_1.Add(self.label_plot_line_16, 0, 0, 0)
        pref_sizer_1.Add(self.tcl_rgb16, 0, 0, 0)
        pref_sizer_1.Add((20, 20), 0, 0, 0)
        pref_sizer_1.Add((20, 20), 0, 0, 0)
        pref_sizer_1.Add((20, 20), 0, 0, 0)
        pref_sizer_1.Add(self.button_color_reset, 0, 0, 0)
        pref_sizer_1.Add(self.chkb_lgd, 0, wx.LEFT, 8)
        pref_sizer_1.Add(self.tcl_lgd, 0, 0, 0)
        pref_sizer_1.Add((20, 20), 0, 0, 0)
        pref_sizer_1.Add((20, 20), 0, 0, 0)
        pref_sizer_1.Add(self.label_glw, 0, wx.LEFT, 30)
        pref_sizer_1.Add(self.radio_linew1, 0, 0, 0)
        pref_sizer_1.Add(self.radio_linew2, 0, 0, 0)
        pref_sizer_1.Add((20, 20), 0, 0, 0)
        pref_sizer_1.Add((200, 80), 0, 0, 0)
        pref_sizer_1.Add(self.cancelButton, 0, wx.ALIGN_BOTTOM, 0)
        pref_sizer_1.Add(self.okButton, 0, wx.ALIGN_BOTTOM, 0)
        self.SetSizer(pref_sizer_1)
        self.Layout()
        # end wxGlade

# end of class EsxPlotPreferencesDialog


class EsxPlotFrame(wx.Frame):
    def __init__(self, *args, **kwds):
        # begin wxGlade: EsxPlotFrame.__init__
        kwds["style"] = wx.DEFAULT_FRAME_STYLE
        wx.Frame.__init__(self, *args, **kwds)
        
        # Menu Bar
        self.menuBar = wx.MenuBar()
        self.menu = wx.Menu()
        self.menu.Append(ID_ABOUT, "About", "version", wx.ITEM_NORMAL)
        self.menu.AppendSeparator()
        self.menu_sub = wx.Menu()
        self.menu_sub_sub = wx.Menu()
        self.menu_sub_sub.Append(ID_IMPORT_DATA_BATCH, "an esxtop batch file", "Load an esxtop batch CSV file", wx.ITEM_NORMAL)
        self.menu_sub_sub.Append(ID_IMPORT_DATA_HOST, "a vSphere host", "Connect to a vSphere host via the SDK", wx.ITEM_NORMAL)
        self.menu_sub.AppendMenu(ID_IMPORT_DATA, "Data Set from...", self.menu_sub_sub, "")
        self.menu_sub.Append(ID_IMPORT_QUERIES, "Queries", "Load your favorite RegEx queries", wx.ITEM_NORMAL)
        self.menu.AppendMenu(ID_IMPORT, "Import", self.menu_sub, "")
        self.menu_sub = wx.Menu()
        self.menu_sub.Append(ID_EXPORT_GRAPHS, "Graph", "Export the plot as an image file", wx.ITEM_NORMAL)
        self.menu_sub.Append(ID_EXPORT_COLS, "Columns", "Export tree selections as a CSV file", wx.ITEM_NORMAL)
        self.menu_sub.Append(ID_EXPORT_QUERIES, "Queries", "Export your favorite queries", wx.ITEM_NORMAL)
        self.menu.AppendMenu(ID_EXPORT, "Export", self.menu_sub, "")
        self.menu.AppendSeparator()
        self.menu_sub = wx.Menu()
        self.menu_sub.Append(ID_CLOSE_DATASET, "Current Data Set", "Close the current dataset and reset esxplot", wx.ITEM_NORMAL)
        self.menu.AppendMenu(ID_CLOSE, "Close", self.menu_sub, "")
        self.menu.AppendSeparator()
        self.menu.Append(ID_PREF, "Preferences", "Preferences", wx.ITEM_NORMAL)
        self.menu.AppendSeparator()
        self.menu.Append(ID_HELP, "Help", "Help", wx.ITEM_NORMAL)
        self.menu.AppendSeparator()
        self.menu.Append(ID_EXIT, "Exit", "Terminate the program", wx.ITEM_NORMAL)
        self.menuBar.Append(self.menu, "File")
        self.SetMenuBar(self.menuBar)
        # Menu Bar end
        self.esxplot_statusbar = self.CreateStatusBar(1, wx.ST_SIZEGRIP)
        self.splitter = wx.SplitterWindow(self, -1, style=wx.SP_3D|wx.SP_BORDER)
        self.leftPanel = wx.Panel(self.splitter, -1, style=wx.DOUBLE_BORDER|wx.TAB_TRAVERSAL)
        self.banner = wx.StaticText(self.leftPanel, -1, "esxplot vCHANGE_ME", style=wx.ALIGN_CENTRE)
        self.textbox = wx.TextCtrl(self.leftPanel, -1, "", style=wx.TE_MULTILINE|wx.TE_READONLY)
        self.searchtext = wx.StaticText(self.leftPanel, -1, "Query Search:")
        self.queryText = wx.TextCtrl(self.leftPanel, -1, "", style=wx.TE_MULTILINE)
        self.queryButton = wx.Button(self.leftPanel, -1, "GO")
        self.tree = MyTreeCtrl(self.leftPanel, 1, wx.DefaultPosition, (-1,-1), wx.TR_HIDE_ROOT|wx.TR_HAS_BUTTONS|wx.TR_MULTIPLE)
        self.rightPanel = wx.Panel(self.splitter, -1, style=wx.DOUBLE_BORDER|wx.RAISED_BORDER)
        self.plotter = MyPlotCanvas(self.rightPanel, -1)

        self.__set_properties()
        self.__do_layout()
        # end wxGlade

    def __set_properties(self):
        # begin wxGlade: EsxPlotFrame.__set_properties
        self.SetTitle("esxplot")
        self.SetSize((1042, 747))
        self.esxplot_statusbar.SetStatusWidths([-1])
        # statusbar fields
        esxplot_statusbar_fields = ["esxplot_statusbar"]
        for i in range(len(esxplot_statusbar_fields)):
            self.esxplot_statusbar.SetStatusText(esxplot_statusbar_fields[i], i)
        self.banner.SetFont(wx.Font(10, wx.DEFAULT, wx.ITALIC, wx.BOLD, 0, ""))
        self.searchtext.SetFont(wx.Font(10, wx.DEFAULT, wx.NORMAL, wx.NORMAL, 0, ""))
        self.queryText.SetMinSize((400, 60))
        self.queryButton.SetMinSize((40, 60))
        self.leftPanel.SetBackgroundColour(wx.Colour(225, 225, 225))
        self.leftPanel.SetFont(wx.Font(10, wx.SWISS, wx.ITALIC, wx.BOLD, 0, ""))
        # end wxGlade

    def __do_layout(self):
        # begin wxGlade: EsxPlotFrame.__do_layout
        sizer_1 = wx.BoxSizer(wx.HORIZONTAL)
        rightBox = wx.BoxSizer(wx.VERTICAL)
        sizer_4 = wx.BoxSizer(wx.VERTICAL)
        leftBox = wx.BoxSizer(wx.HORIZONTAL)
        sizer_4.Add(self.banner, 0, wx.LEFT, 4)
        sizer_4.Add(self.textbox, 0, wx.ALL|wx.EXPAND, 4)
        sizer_4.Add(self.searchtext, 0, wx.ALL, 10)
        leftBox.Add(self.queryText, 1, wx.LEFT|wx.EXPAND, 4)
        leftBox.Add(self.queryButton, 0, wx.LEFT|wx.EXPAND, 8)
        sizer_4.Add(leftBox, 1, wx.EXPAND, 0)
        sizer_4.Add(self.tree, 6, wx.ALL|wx.EXPAND, 4)
        self.leftPanel.SetSizer(sizer_4)
        rightBox.Add(self.plotter, 1, wx.EXPAND, 0)
        self.rightPanel.SetSizer(rightBox)
        self.splitter.SplitVertically(self.leftPanel, self.rightPanel)
        sizer_1.Add(self.splitter, 1, wx.EXPAND, 0)
        self.SetSizer(sizer_1)
        self.Layout()
        # end wxGlade

# end of class EsxPlotFrame


if __name__ == "__main__":
    esxplot_gui = wx.PySimpleApp(0)
    wx.InitAllImageHandlers()
    esxplot = EsxPlotFrame(None, -1, "")
    esxplot_gui.SetTopWindow(esxplot)
    esxplot.Show()
    esxplot_gui.MainLoop()
